export const GET_ERRORS = "GET_ERRORS";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_USER_GAMESCORE = "SET_USER_GAMESCORE";
export const GET_USER_GAMESCORE = "GET_USER_GAMESCORE";
